project/simple_flask/forms.py
# import module
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


from flask_wtf.file import FileField, FileAllowed, FileRequired
# from project import images


# make a form using class
from project import ALLOWED_EXTENSION


class AddPostForm(Form):
    post_title = StringField("Post Title", validators=[DataRequired()])
    post_detail = StringField("Post Detail ", validators=[DataRequired()])
    post_image = FileField(label='File Image', validators=[FileRequired(), FileAllowed(upload_set=ALLOWED_EXTENSION, message='Image Only')])
    #  add form to post image
    # post_image = FileField('Cover Post Image', validators=[FileRequired(), FileAllowed(upload_set=, message='image only')])

class EditPostForm(Form):
    post_title = StringField(label='New Post Title: ', validators=[DataRequired()])
    post_detail = StringField(label='New Post Detail', validators=[DataRequired()])

project/simple_flask/views.py
# import module
import os

from flask import render_template, Blueprint, request, redirect, url_for, flash, send_from_directory
from flask_login import login_required, current_user
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename

from project import db, ALLOWED_EXTENSION, app
# import models
from project.models import Simple_Flask_App, User
# config
from project.simple_flask.forms import AddPostForm, EditPostForm

simple_flask_blueprint = Blueprint('simple_flask', __name__, template_folder='templates')


# route
@simple_flask_blueprint.route('/')
def index():
    return render_template('index.html')

# route to dispaly image
@simple_flask_blueprint.route('/images')
def image_list():
    files = os.listdir(app.config['UPLOAD_FOLDER'])
    return render_template('images_list.html', image_list=files)


# create route to display publoc post
@simple_flask_blueprint.route('/public')
def public_post():
    public = Simple_Flask_App.query.filter_by(is_public=True)
    return render_template('public_post.html', posts=public)


# route to display post
@simple_flask_blueprint.route('/posts')
@login_required
def all_public_user_posts():
    all_user_posts = Simple_Flask_App.query.filter_by(user_id=current_user.id)
    return render_template('user_posts.html', posts=all_user_posts)


# route for add data from form
@simple_flask_blueprint.route('/add', methods=['GET', 'POST'])
def add_posts():
    form = AddPostForm(CombinedMultiDict((request.files, request.form)))
    if request.method == 'POST':
        if form.validate_on_submit():
            file = form.post_image.data
            filename = secure_filename(filename=file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            new_post = Simple_Flask_App(title=form.post_title.data, detail=form.post_detail.data,
                                        user_id=current_user.id, is_public=True, image_filename=file.filename)
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('simple_flask.public_post'))

    return render_template('add_post.html', form=form)


@simple_flask_blueprint.route('/delete/<post_id>')
def post_delete(post_id):
    data = db.session.query(Simple_Flask_App, User).join(User).filter(Simple_Flask_App.id == post_id).first()
    if current_user.is_authenticated and data.Simple_Flask_App.user_id == current_user.id:
        data = Simple_Flask_App.query.filter_by(id=post_id).first()
        db.session.delete(data)
        db.session.commit()
        flash('Post deleted successfully', category='success')

    return redirect(url_for('simple_flask.all_public_user_posts'))

# add edit data route
@simple_flask_blueprint.route('/edit/<post_id>', methods=['GET', 'POST'])
def edit_posts(post_id):
    data = db.session.query(Simple_Flask_App, User).join(User).filter(Simple_Flask_App.id == post_id).first()
    form = EditPostForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            if current_user.is_authenticated and data.Simple_Flask_App.user_id == current_user.id:
                data = Simple_Flask_App.query.filter_by(id=post_id).first()
                new_post_title = form.post_title.data
                new_post_detail = form.post_detail.data
                try:
                    data.post_title = new_post_title
                    data.post_detail = new_post_detail
                    db.session.commit()
                except Exception as e:
                    return {'error': str(e)}
            return redirect(url_for('simple_flask.all_public_user_posts'))
    return render_template('edit_post.html', form=form, posts=data)

# add post detail
@simple_flask_blueprint.route('/posts/<post_id>')
def posts_detail(post_id):
    posts_with_user = db.session.query(Simple_Flask_App, User).join(User).filter(Simple_Flask_App.id == post_id).first()
    if posts_with_user is not None:
        if posts_with_user.Simple_Flask_App.is_public:
            return render_template('posts_detail.html', posts=posts_with_user)
        else:
            if current_user.is_authenticated and posts_with_user.Simple_Flask_App.user_id == current_user.id:
                return render_template('posts_detail.html', posts=posts_with_user)
            else:
                flash('Error incorrect Permissions', category='error')
    else:
        flash('Post Not Found or does not exists', category='error')
    return redirect(url_for('simple_flask.index'))


def allowed_file(file):
    return '.' in file and file.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSION


# @simple_flask_blueprint.route('/uploads', methods=['GET', 'POST'])
# def upload_image():
#     file = request.files['file']
#     if 'file' not in request.files:
#         flash('Choice some image to Upload', category='error')
#         # return redirect(url_for('simple_flask.upload_image'))
#
#     if file.filename == '':
#         flash('Choice some Image to Uploads', category='error')
#         return redirect(url_for('simple_flask.upload_image'))
#
#     if file and allowed_file(file=file.filename):
#         filename = secure_filename(file.filename)
#         file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
#         flash('Upload Image success', category='success')
#         return redirect(url_for('simple_flask.upload_image'))
#
#
#     return render_template('upload.html')


# new route for display image
@simple_flask_blueprint.route('/media/<filename>')
def display_name(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

project/users/views.py
# import module
from datetime import datetime
from threading import Thread

from flask import render_template, Blueprint, request, redirect, flash, url_for
from flask_login import login_user, login_required, current_user, logout_user
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from werkzeug.exceptions import abort

from project import db, mail, app
# import models
from project.models import User

# import forms
from project.users.forms import RegisterForm, LoginForm, EmailForm, PasswordForm

# import error handler
from sqlalchemy.exc import IntegrityError

# config
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# routing

# routing for user profile
@users_blueprint.route('/user_profile')
@login_required
def show_profile():
    return render_template('profile.html')


# @users_blueprint.route('/posts/<int:post_id>')
# def show_post():
#     return render_template('post.html')


# add function helper async send email
def send_async_email(message):
    with app.app_context():
        mail.send(message)


# add function helper to send email
def send_email(subject, recipients, html_body):
    message = Message(subject=subject, recipients=recipients)
    # message.body = text_body
    message.html = html_body
    # add treading
    tread = Thread(target=send_async_email, args=[message])
    tread.start()

    # send email
    # mail.send(message)


# add function helper to handle sending email with unique token
def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for('users.confirm_email',
                          token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'), _external=True)

    html = render_template('email_confirmation.html', confirm_url=confirm_url)

    send_email('Confirm your Email Address', [user_email], html_body=html)


# add helper to send link password reset
def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(secret_key=app.config['SECRET_KEY'])
    password_reset_url = url_for('users.reset_with_token',
                                 token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
                                 _external=True)

    html = render_template('email_password_reset.html', password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html_body=html)


# route for password reset with token
@users_blueprint.route('/reset/<token>', methods=['GET', 'POST'])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(secret_key=app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('Password Reset Link has Expired or invalid', category='error')
        return redirect(url_for('users.show_login'))

    form = PasswordForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid Email Address', category='error')
            return redirect(url_for('users.show_login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your Password Has been Updated', category='success')
        return redirect(url_for('users.show_login'))
    return render_template('reset_password_with_token.html', form=form, token=token)


# route for password_reset
@users_blueprint.route('/reset', methods=['GET', 'POST'])
def reset_password():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('invalid email address', category='error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user_email=user.email)
            flash('Please check in your email for password reset', category='success')
        else:
            flash('Your Email Address must be confirmed before attempting a password reset', category='error')

        return redirect(url_for('users.show_login'))
    return render_template('password_reset_email.html', form=form)


# create New Route for Email Change
@users_blueprint.route('/email_change', methods=['GET', 'POST'])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_send_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()

                    # send email confirmation again
                    send_confirmation_email(user_email=user.email)
                    flash('email success to Changed, Please Confirm Again, (Link Send To New Email)',
                          category='success')
                    return redirect(url_for('users.show_profile'))
                else:
                    flash('Sorry That Email has Already Exist', category='error')

            except IntegrityError:
                flash('Error That Email Has Already Exist', category='error')

    return render_template('email_change.html', form=form)

# defining route to change password
@users_blueprint.route('/password_change', methods=['GET', 'POST'])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('password has been updated', category='success')
            return redirect(url_for('users.show_profile'))

    return render_template('password_change.html', form=form)

# create new route for resend email confirmation
@users_blueprint.route('/resend_confirmation', methods=['GET', 'POST'])
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email Send To Confirm your Email', category='info')
    except IntegrityError:
        flash('Error Unable to Send Email Confirm', category='error')
    
    return redirect(url_for('users.show_profile'))

# add route for admin views users
@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_user():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('admin_view_user.html', users=users)

    return render_template('simple_flask.index')


# defining route to register users
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(email=form.email.data, plaintext_password=form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.create_all()
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)

                # add flash message with email
                # message = Message(
                #     subject="Halo Python",
                #     body="Halo with Python",
                #     recipients=["tkjasikk@gmail.com"]
                # )
                #
                # mail.send(message)
                # send_email('Say Hello With Python', ['tkjasikk@gmail.com'], 'Hello im Pery, i wanna say hello world with python', '<h3>This is HTML</h3>')

                flash('Register Done', category='success')
                return redirect(url_for('simple_flask.index'))

            except IntegrityError:
                db.session.rollback()
                flash('ERROR Email {} has already exists'.format(form.email.data), category='error')

    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def show_login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                # last login logic
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Login is successful', category='success')
                return redirect(url_for('simple_flask.index'))
            else:
                flash('ERROR Incorrect Credentials', category='error')
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def show_logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Good bye', category='info')
    return redirect(url_for('users.show_login'))


# add new route for confirm email
@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:

project/simple_flask/templates/_form_macros.html
{% macro render_field(field) %}

<dt>{{field.label}}:
    <dd>{{field(**kwargs)|safe}}
        
        {% if field.errors %}
            <span class="error">
                {% for error in field.errors %}
                  {{error}}
                {% endfor %}
            </span>
        {% endif %}
    </dd>
{% endmacro %}

project/simple_flask/templates/add_post.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field with context %}

{% block contents %}
  <div class="container">
    <h2>Add New Post</h2>
    <!-- link static css -->
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
  
    <form action="{{url_for('simple_flask.add_posts')}}" method="post" enctype="multipart/form-data">
        {{form.csrf_token}}
  
        <dl>
          {{render_field(form.post_title)}}
          {{render_field(form.post_detail)}}
          {{render_field(form.post_image)}}
        </dl>
  
        <!-- {{form.post_title(placeholder='Enter post Title')}}
        post title error handler -->
  
        <!-- <span class="error">
          
          {% if form.post_title.error %}
            {% for error in form.post_title.error %}
                {{error}}
            {% endfor %}
          {% endif %}
        </span>
          
        <span class="error">
          {{form.post_detail(placeholder='Enter Post Discription')}}
          post detail error handler -->
          
          <!-- {% if form.post_detail.error %}
            {% for error in form.post_detail.error %}
                {{error}}
            {% endfor %}
          {% endif %}
        </span> -->
  
        <button type="submit" class="btn btn-primary">Add Post</button>
    </form>
  </div>
{% endblock contents %}

project/simple_flask/templates/apps_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Simple Flask App</title>
</head>
<body>
  <!-- Favicon -->
  <link href="{{ url_for('static', filename='assets/img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/icofont/icofont.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/animate.css/animate.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/venobox/venobox.css') }}" rel="stylesheet">
  
  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">

  <!-- Header section -->
  <header id="header">
    <div class="container d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{{ url_for('simple_flask.index') }}"><span>Simple Flask App</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <!-- navbar section -->
      <nav class="nav-menu d-none d-lg-block">
        <ul>
          
          {% if current_user.is_authenticated %}
          <li class="active"><a href="{{ url_for('simple_flask.index') }}">Home</a></li>
          <li><a href="{{ url_for('simple_flask.public_post') }}">Public Post</a></li>
          <li><a href="{{ url_for('simple_flask.image_list') }}">Image List</a></li>
          <li><a href="{{ url_for('users.show_profile') }}">Profile User</a></li>
          
          <li class="drop-down"><a href="">Admin Menu</a>
            <ul>
              <li><a href="{{ url_for('simple_flask.add_posts') }}">Add New Post</a></li>
              <li><a href="{{ url_for('simple_flask.all_public_user_posts') }}">Users Post</a></li>
              <li class="drop-down"><a href="{{ url_for('users.admin_view_user') }}">User List</a></li>
              <li><a href="{{ url_for('users.show_logout') }}">Logout</a></li>
            </ul>
          </li>

          {% else %}
          <li class="active"><a href="{{ url_for('simple_flask.index') }}">Home</a></li>
          <li><a href="{{ url_for('simple_flask.public_post') }}">Public Post</a></li>
          <li><a href="{{ url_for('simple_flask.image_list') }}">Image List</a></li>
          <li><a href="{{ url_for('users.show_login') }}">Login</a></li>
          <li><a href="{{ url_for('users.register') }}">Register</a></li>
          {% endif %}
            
          
        </ul>
      </nav>
      <!-- end navbar section -->
  </header>
  <!-- end header section -->
  
  
  {% block contents %}
    
  {% endblock contents %}


  <!-- Javascript sources -->

  <script src="{{ url_for('static', filename='assets/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/jquery.easing/jquery.easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/jquery-sticky/jquery.sticky.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/waypoints/jquery.waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/counterup/counterup.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/owl.carousel/owl.carousel.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/venobox/venobox.min.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
</body>
</html>

project/simple_flask/templates/edit_post.html
{% extends "apps_templates.html" %}

{% block contents %}
  <div class="conteiner">
    {{super()}}
    <div class="row">
        <div class="page-header">
            <h4>Edit Book Page</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-heading"></div>
                    <div class="card-body">
                        <form action="{{url_for('simple_flask.edit_posts', post_id=posts.Simple_Flask_App.id)}}" method="post">
                            {{form.csrf_token}}
                            {{form.post_title(value=posts.Simple_Flask_App.post_title)}}
                            {{form.post_detail(value=posts.Simple_Flask_App.post_detail)}}
                            <button class="btn btn-sm btn-success" type="submit">Update Post</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock contents %}

project/simple_flask/templates/images_list.html
{% extends "apps_templates.html" %}


{% block contents %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for image in image_list %}
          <div class="col">
              <div class="card">
                  <img class="card-img-top" src="{{url_for('simple_flask.display_name', filename=image)}}" alt="{{image.filename}}" srcset="">
                  <h5>File Name: {{image}}</h5>
              </div>
          </div>
        {% endfor %}
    </div>
</div>
{% endblock contents %}

project/simple_flask/templates/layout.html
{% extends "apps_templates.html" %}

{% block contents %}
    <!--  tabel-->
    <table class="table">
      <thead>
        <tr>
          <th scope="col">No. </th>
          <th scope="col">Posts List</th>
          <th scope="col">Posts Detail</th>
        </tr>
      </thead>
        <tbody>
          {% for post in all_posts %}
            <tr>
              <th scope="row">{{loop.index}}</th>
              <td>{{post.post_title}}</td>
              <td>{{post.post_detail}}</td>

          {% endfor %}
        </tbody>
    </table>
<!--end of table-->
{% endblock contents %}

project/simple_flask/templates/posts_detail.html
{% extends "apps_templates.html" %}

{% block contents %}
  <div class="page-header">
      Posts Title: <h4>{{posts.Simple_Flask_App.post_title}}</h4>
  </div>

  <div class="row">
      <div class="card">
          <div class="card-header">Posts Discrption</div>
          <div class="card-body">{{posts.Simple_Flask_App.post_detail}}</div>
      </div>

      <div class="card">
          <div class="card-header">Posts Status</div>
          
          {% if posts.Simple_Flask_App.is_public %}
              <div class="card-body">Status: Public</div>
              {% else %}
              <div class="card-body">Status: Private</div>
          {% endif %}
      </div>

      <div class="card">
          <div class="card-header">User</div>
          <div class="card-body">Active User: {{posts.User.email}}</div>
      </div>
  </div>
{% endblock contents %}

project/simple_flask/templates/public_post.html
{% extends "apps_templates.html" %}

{% block contents %}
    <div class="container">
      <div class="page-header">
        <h2>All Public Post</h2>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Post Detail</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr>
                    <td><a href="{{url_for('simple_flask.posts_detail', post_id=post.id)}}">{{post.post_title}}</a></td>
                    <td>{{post.post_detail}}</td>
                    <td>
                      <button class="btn btn-sm btn-danger"><a href="{{url_for('simple_flask.post_delete', post_id=post.id)}}">Delete Data</a></button>
                      <button class="btn btn-sm btn-info"><a href="{{url_for('simple_flask.edit_posts', post_id=post.id)}}">Edit Data</a></button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>   
{% endblock contents %}

project/simple_flask/templates/update_post.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field with context %}
{% block contents %}
  <h2>Add New Post</h2>
  <!-- link static css -->
  <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">

  <form action="{{url_for('simple_flask.add_posts')}}" method="post" enctype="multipart/form-data">
      {{form.csrf_token}}

      <dl>
        {{render_field(form.post_title)}}
        {{render_field(form.post_detail)}}
        {{render_field(form.post_image)}}
      </dl>

      <!-- {{form.post_title(placeholder='Enter post Title')}}
      post title error handler -->

      <!-- <span class="error">
        
        {% if form.post_title.error %}
          {% for error in form.post_title.error %}
              {{error}}
          {% endfor %}
        {% endif %}
      </span>
        
      <span class="error">
        {{form.post_detail(placeholder='Enter Post Discription')}}
        post detail error handler -->
        
        <!-- {% if form.post_detail.error %}
          {% for error in form.post_detail.error %}
              {{error}}
          {% endfor %}
        {% endif %}
      </span> -->

      <button type="submit" class="btn btn-primary">Add Post</button>
  </form>
{% endblock contents %}

project/simple_flask/templates/upload.html
{% extends "apps_templates.html" %}

{% block contents %}
  <form action="{{url_for('simple_flask.upload_image')}}" enctype="multipart/form-data" method="POST">
    <input type="file" name="file">
    <input type="submit" value="upload image">
  </form>
{% endblock contents %}

project/simple_flask/templates/user_posts.html
{% extends "apps_templates.html" %}

{% block contents %}
    <div class="container">
      <div class="page-header">
        <h2>Users Post</h2>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Post Detail</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr>
                    <td><a href="{{url_for('simple_flask.posts_detail', post_id=post.id)}}">{{post.post_title}}</a></td>
                    <td>{{post.post_detail}}</td>
                    <td>
                      <button class="btn btn-sm btn-danger"><a href="{{url_for('simple_flask.post_delete', post_id=post.id)}}">Delete Data</a></button>
                      <button class="btn btn-sm btn-info"><a href="{{url_for('simple_flask.edit_posts', post_id=post.id)}}">Delete Data</a></button>
                    </td>
                </tr>              
            {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock contents %}