project/users/forms.py
# import module
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email


# Creating Class for Email Form
class EmailForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])


# Create Class For Password Form
class PasswordForm(Form):
    password = PasswordField('Password', validators=[DataRequired()])


# create Class for Register User FORMS
class RegisterForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])


# create class for LoginForms
class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired()])

project/users/views.py
# import module
from datetime import datetime
from threading import Thread

from flask import render_template, Blueprint, request, redirect, flash, url_for
from flask_login import login_user, login_required, current_user, logout_user
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from werkzeug.exceptions import abort

from project import db, mail, app
# import models
from project.models import User

# import forms
from project.users.forms import RegisterForm, LoginForm, EmailForm, PasswordForm

# import error handler
from sqlalchemy.exc import IntegrityError

# config
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# routing

# routing for user profile
@users_blueprint.route('/user_profile')
@login_required
def show_profile():
    return render_template('profile.html')


# @users_blueprint.route('/posts/<int:post_id>')
# def show_post():
#     return render_template('post.html')


# add function helper async send email
def send_async_email(message):
    with app.app_context():
        mail.send(message)


# add function helper to send email
def send_email(subject, recipients, html_body):
    message = Message(subject=subject, recipients=recipients)
    # message.body = text_body
    message.html = html_body
    # add treading
    tread = Thread(target=send_async_email, args=[message])
    tread.start()

    # send email
    # mail.send(message)


# add function helper to handle sending email with unique token
def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for('users.confirm_email',
                          token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'), _external=True)

    html = render_template('email_confirmation.html', confirm_url=confirm_url)

    send_email('Confirm your Email Address', [user_email], html_body=html)


# add helper to send link password reset
def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(secret_key=app.config['SECRET_KEY'])
    password_reset_url = url_for('users.reset_with_token',
                                 token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
                                 _external=True)

    html = render_template('email_password_reset.html', password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html_body=html)


# route for password reset with token
@users_blueprint.route('/reset/<token>', methods=['GET', 'POST'])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(secret_key=app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('Password Reset Link has Expired or invalid', category='error')
        return redirect(url_for('users.show_login'))

    form = PasswordForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid Email Address', category='error')
            return redirect(url_for('users.show_login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your Password Has been Updated', category='success')
        return redirect(url_for('users.show_login'))
    return render_template('reset_password_with_token.html', form=form, token=token)


# route for password_reset
@users_blueprint.route('/reset', methods=['GET', 'POST'])
def reset_password():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('invalid email address', category='error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user_email=user.email)
            flash('Please check in your email for password reset', category='success')
        else:
            flash('Your Email Address must be confirmed before attempting a password reset', category='error')

        return redirect(url_for('users.show_login'))
    return render_template('password_reset_email.html', form=form)


# create New Route for Email Change
@users_blueprint.route('/email_change', methods=['GET', 'POST'])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_send_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()

                    # send email confirmation again
                    send_confirmation_email(user_email=user.email)
                    flash('email success to Changed, Please Confirm Again, (Link Send To New Email)',
                          category='success')
                    return redirect(url_for('users.show_profile'))
                else:
                    flash('Sorry That Email has Already Exist', category='error')

            except IntegrityError:
                flash('Error That Email Has Already Exist', category='error')

    return render_template('email_change.html', form=form)

# defining route to change password
@users_blueprint.route('/password_change', methods=['GET', 'POST'])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('password has been updated', category='success')
            return redirect(url_for('users.show_profile'))

    return render_template('password_change.html', form=form)

# create new route for resend email confirmation
@users_blueprint.route('/resend_confirmation', methods=['GET', 'POST'])
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email Send To Confirm your Email', category='info')
    except IntegrityError:
        flash('Error Unable to Send Email Confirm', category='error')
    
    return redirect(url_for('users.show_profile'))

# add route for admin views users
@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_user():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('admin_view_user.html', users=users)

    return render_template('simple_flask.index')


# defining route to register users
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(email=form.email.data, plaintext_password=form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.create_all()
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)

                # add flash message with email
                # message = Message(
                #     subject="Halo Python",
                #     body="Halo with Python",
                #     recipients=["tkjasikk@gmail.com"]
                # )
                #
                # mail.send(message)
                # send_email('Say Hello With Python', ['tkjasikk@gmail.com'], 'Hello im Pery, i wanna say hello world with python', '<h3>This is HTML</h3>')

                flash('Register Done', category='success')
                return redirect(url_for('simple_flask.index'))

            except IntegrityError:
                db.session.rollback()
                flash('ERROR Email {} has already exists'.format(form.email.data), category='error')

    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def show_login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                # last login logic
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Login is successful', category='success')
                return redirect(url_for('simple_flask.index'))
            else:
                flash('ERROR Incorrect Credentials', category='error')
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def show_logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Good bye', category='info')
    return redirect(url_for('users.show_login'))


# add new route for confirm email
@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:

project/users/templates/admin_view_user.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
<div class="page-header">
    <h4>Administrative Page: List of User</h4>
</div>

<div class="row">
    <table class="table table-striped" id="admin_list_of_users">
        <thead>
            <tr class="table-dark">
                <th>User ID</th>
                <th>Email</th>
                <th>Role</th>
                <th>Registration Date</th>
                <th>Email Confirm Status</th>
                <th>Email Confirmed on</th>
                <th>Last Login</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
              <tr>
                  <td>{{user.id}}</td>
                  <td>{{user.email}}</td>
                  <td>{{user.role}}</td>
                  <td>{{user.registered_on}}</td>
                  <td>{{user.email_confirmed}}</td>
                  <td>{{user.email_confirmed_on}}</td>
                  <td>{{user.last_logged_in}}</td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock contents %}

project/users/templates/email_change.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
    <div class="container" style="margin-top: 30px;">
        <div class="page-header">
            <h2>Email Change</h2>
        </div>
    
        <h4>Current Email {{ current_user.email }}</h4>
        <p>Please Enter Your New Email</p>
        <form action="{{ url_for('users.user_email_change') }}" method="POST">
            {{form.csrf_token}}
            <dl>
                {{render_field(form.email, placeholder="Enter New Email Address")}}
            </dl>
            <button type="submit" class="btn btn-sm btn-success">Update Email</button>
        </form>
    </div>
{% endblock contents %}

project/users/templates/email_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
</head>
<body>
    <p>Your Account on Simple App Has Successfully Created Please click Link in bellow to activate your account</p>
    <a href="{{confirm_url}}">{{confirm_url}}</a>
    <p>thanks by pery1050@gmail.com</p>

</body>
</html>

project/users/templates/email_password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Confirm</title>
</head>
<body>
    <p>Your Reset Password Requested has been ready, Please Click Link Bellow</p>
    <p><a href="{{password_reset_url}}">{{password_reset_url}}</a></p>
    <br>
    <p>Thanks for use our Application</p>
</body>
</html>

project/users/templates/login.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
  <div class="container" style="margin-top: 30px;">
    <div class="user-registration">
        <div class="page-header">
            <h4>Log In</h4>
        </div>
        <form action="{{url_for('users.show_login')}}" method="POST">
            {{form.csrf_token}}
            <dl>
                {{render_field(form.email, placeholder="Email Address")}}
                {{render_field(form.password, placeholder="Password")}}
            </dl>
            <button type="submit" class="btn btn-sm btn-success">Login</button>
        </form>
        <em>Need an Accounts?</em> <a href="{{url_for('users.register')}}">Register</a><br>
        <em>Forgot Password..? </em><a href="{{url_for('users.reset_password')}}">Reset Your Password</a>
    </div>
  </div>
{% endblock contents %}

project/users/templates/password_change.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
    <div class="container" style="margin-top: 30px;">
        <div class="page-header">
            <h2>Password Change</h2>
        </div>
    
        <p>Please Enter New Password</p>
        <form action="{{ url_for('users.user_password_change') }}" method="POST">
            {{form.csrf_token}}
            <dl>
                {{render_field(form.password, placeholder="Enter New Password")}}
            </dl>
            <button type="submit" class="btn btn-sm btn-info">Update Password</button>
        </form>
    </div>
{% endblock contents %}

project/users/templates/password_reset_email.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
  <div class="container" style="margin-top: 30px;">
    <div class="page-header">
        <h2>Email Address: </h2>
    </div>
    <form action="{{url_for('users.reset_password')}}" method="POST">
        {{form.csrf_token}}
        <dl>
            {{render_field(form.email, placeholder="Enter Your Email Address")}}
        </dl>
        <button class="btn btn-sm btn-success" type="submit">Submit</button>
    </form>
  </div>
{% endblock contents %}

project/users/templates/profile.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
  <div class="user-profile">
      <div class="page-header">
          <h2>User Profile</h2>
      </div>
      
      <div class="row">
          <div class="col-sm-6">
              <div class="card">
                  <div class="card card-header">Email Address:</div>
                  <div class="card-body">{{current_user.email}}</div>
              </div>

              <div class="card">
                  <div class="card-header">Account Action</div>
                  <div class="card-body"><a href="{{ url_for('users.user_email_change') }}">Change Email</a></div>
                  <div class="card-body"><a href="{{ url_for('users.user_password_change') }}">Change Password</a></div>

                  
                  {% if not current_user.email_confirmed %}
                      <div class="card-body"><a href="{{url_for('users.resend_email_confirmation')}}">Resend Email Confirmation Again</a></div>
                  {% endif %}
                      
              </div>

              <div class="card">
                  <div class="card-header">Statistics</div>
                  <div class="card-body"> Member Since: {{current_user.registered_on.strftime("%A %B %d, %Y")}}</div>
                  
                  {% if current_user.last_logged_in != None %}
                      <div class="card-body">Last Logged In: {{current_user.last_logged_in.strftime("%A %B %d, %Y")}}</div>
                      
                  {% else %}
                    <div class="card-body">First Time Logged In, Welcome </div>
                  {% endif %}
                  
                  {% if current_user.email_confirmed %}
                    <div class="card-body">Email Confirmed on: {{current_user.email_confirmed_on.strftime("%A %B %d, %Y")}}</div>
                  {% else %}
                    <div class="card-body">Email has not been confirmed</div>
                  {% endif %}
                      
              </div>
          </div>
      </div>
  </div>
{% endblock contents %}

project/users/templates/register.html
{% extends 'apps_templates.html' %}

{% from "_form_macros.html" import render_field %}

{% block contents %}
  <div class="container" style="margin-top: 30px;">
    <div class="user-registration">
        <div class="page-header">
            <h4>Please Register your accounts</h4>
        </div>
        <form action="{{url_for('users.register')}}" method="POST">
            {{form.csrf_token}}
            <dl>
                {{render_field(form.email, placeholder="Email Address")}}
                {{render_field(form.password, placeholder="Password")}}
                {{render_field(form.confirm, placeholder="Confirm Password")}}
            </dl>
            <button class="btn btn-primary btn-sm" type="submit">Create New Account</button>
        </form>
    </div>
  </div>
{% endblock contents %}

project/users/templates/reset_password_with_token.html
{% extends "apps_templates.html" %}
{% from "_form_macros.html" import render_field %}

{% block contents %}
  <div class="container" style="margin-top: 30px;">
    <div class="page-header">
        <h2>New Password: </h2>
    </div>
    <form action="{{url_for('users.reset_with_token', token=token)}}" method="POST">
        {{form.csrf_token}}
        <dl>
            {{render_field(form.password, placeholder="Enter New Password")}}
        </dl>
        <button type="submit" class="btn btn-sm btn-success">Update Password</button>
    </form>
  </div>
{% endblock contents %}